# MySQL. Versions 5.5.8 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["COINGATE_DATABASE_USERNAME"] %>
  password: <%= ENV["COINGATE_DATABASE_PASSWORD"] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: coingate_development

test:
  <<: *default
  database: coingate_test

production:
  <<: *default
  database: coingate_production
  username: <%= ENV["COINGATE_DATABASE_USERNAME"] %>
  password: <%= ENV["COINGATE_DATABASE_PASSWORD"] %>
